### Numpy 연습문제
**필요한 모듈은 import 하여 사용합니다.**

---

In [31]:
# 이곳에 필요한 모듈 import 한 후 실행
import numpy as np

from load_utils import load_one_stock, load_dates, load_matrix

1. 다음 리스트 [1, 2, 3, 4, 5]를 ndarray로 변환하고, 배열의 차원(ndim)과 형태(shape)을 출력하시오.

In [3]:
list = [1,2,3,4,5]
arr = np.array(list)
print(f"차원: {arr.ndim} / 형태: {arr.shape}")

차원: 1 / 형태: (5,)


2. np.arange()를 이용해 0부터 20까지의 짝수로 이루어진 배열을 생성하시오.

In [8]:
arr = np.arange(0,21,2)
"""
arr = np.arange(21)
arr = arr[arr % 2 == 0]
"""
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


3. 다음 제시된 배열에서, 3 이상인 값만 추출하는 불리언 인덱싱 코드를 작성하시오.

In [10]:
list3 = [1,3,5,2,8,3]
arr = np.array(list3)
arr = arr[arr>3]
print(arr)

[5 8]


4. 다음 제시된 리스트를 배열로 변환한 후, 두 번째 행만 슬라이싱하여 출력하시오.

In [11]:
list4 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
arr = np.array(list4)
print(arr[1::2])

[[40 50 60]]


5. 다음 제시된 리스트를 배열로 변환한 후, 모든 홀수에만 10을 더하는 벡터화 연산을 수행하시오.

In [14]:
list5 = [1, 2, 3, 4, 5]
arr = np.array(list5)
arr = np.where(arr % 2 != 0, arr + 10, arr)
print(arr)

[11  2 13  4 15]


6. 다음 제시된 실수 리스트를 배열로 변환한 후, 반올림한 정수형 배열로 변환하시오.\
   주의 : astype 만 쓰면 소수점 아래가 버려져서 값이 새어나간다.

    - [출력 예시]
        - np.array([52000.9, -3.7]) -> [52001, -4]

    - [힌트] 반올림을 먼저 하고 타입을 바꾼다. 순서가 중요하다.

In [15]:
list6 = [52000.9, 51999.2, -3.7, 52000.5]
arr = np.array(list6)
arr = np.round(arr,0)
arr = np.astype(arr,'int64')
print(arr)

[52001 51999    -4 52000]


#### == 아래 문제들은 실습용 데이터(prices.csv, load_utils.py)를 활용하여 풀이해보세요. ==

7. 첫 종목의 종가 데이터를 기준으로 최저가, 최고가와 그에 해당하는 날짜를 각각 출력하시오. \
    (실습용 데이터의 prices 와 dates 는 길이와 순서가 같다.)

    - [출력 예시]
        - (25899, numpy.datetime64('2023-10-16'), 8885, numpy.datetime64('2026-05-21'))

    - [힌트] max 는 '값', argmax 는 '그 값이 있는 위치' 다.\
            위치를 얻으면 길이가 같은 다른 배열에서 같은 자리를 꺼낼 수 있다.

In [20]:
prices = load_one_stock(0).copy()
dates = load_dates().copy()
max_idx = np.argmax(prices)
min_idx = np.argmin(prices)
print(f"{np.max(prices)}, {dates[max_idx]}, {np.min(prices)}, {dates[min_idx]}")

25899, 2023-10-16, 8885, 2026-05-21


8. 종가 데이터를 기준으로 각 종목별 평균가와, 날짜별 평균가를 구하시오. 
    또한, 각 종목에서 자기 평균을 뺀 배열을 구하시오.
    
    [힌트]
    - 종목별 평균가 : (종목 수,) 배열 
    
    - 날짜별 평균가 : (날짜 수,) 배열
    
    - 각 종목에서 자기 평균을 뺀 배열 : (종목 수, 날짜 수) 배열 \
        결과의 종목별 평균은 0 이 되어야 한다.

In [33]:
matrix = load_matrix().copy()
stock_mean = matrix.mean(axis = 1)
daily_mean = matrix.mean(axis = 0)
print(stock_mean.shape, daily_mean.shape)
stock_mean = stock_mean.reshape(120,1)
print((matrix-stock_mean).mean(axis = 1).max())

(120,) (750,)
2.7318795522054036e-11
